export enum GATEWAY_MESSAGE_TYPE {
  USER_DISCONNECTED = 'USER_DISCONNECTED',
  USER_CONNECTED = 'USER_CONNECTED',
  MESSAGE = 'MESSAGE',
  READ_MESSAGES = 'READ_MESSAGES',
}

export const GATEWAY_INCOMING_MESSAGE_TYPE = {
  SEND_MESSAGE: 'SEND_MESSAGE',
  READ_MESSAGES: 'READ_MESSAGES',
} as const;
