#----------------Actions --------------------------------------------------

up: ## Start all containers
	docker compose up
down: ## Stop all containers
	docker compose down
build: ## Build image	
	docker compose build

