export enum AVAILABLE_LANGUAGE {
  ENGLISH = 'en',
  SPANISH = 'es',
  FRENCH = 'fr',
  GERMAN = 'de',
  CHINESE_SIMPLIFIED = 'zh-CN',
  CHINESE_TRADITIONAL = 'zh-TW',
  JAPANESE = 'ja',
  KOREAN = 'ko',
  PORTUGUESE = 'pt',
  RUSSIAN = 'ru',
  ITALIAN = 'it',
  DUTCH = 'nl',
  ARABIC = 'ar',
  HINDI = 'hi',
  BENGALI = 'bn',
  TURKISH = 'tr',
  POLISH = 'pl',
  SWEDISH = 'sv',
  GREEK = 'el',
  HEBREW = 'he',
  VIETNAMESE = 'vi',
  THAI = 'th',
  CZECH = 'cs',
  HUNGARIAN = 'hu',
  ROMANIAN = 'ro',
  DANISH = 'da',
  FINNISH = 'fi',
  NORWEGIAN = 'no',
  UKRAINIAN = 'uk',
  MALAY = 'ms',
  INDONESIAN = 'id',
  FILIPINO = 'tl',
  PERSIAN = 'fa',
  URDU = 'ur',
  TAMIL = 'ta',
  TELUGU = 'te',
  MARATHI = 'mr',
  BURMESE = 'my',
  SERBIAN = 'sr',
  CROATIAN = 'hr',
  SLOVAK = 'sk',
  SLOVENIAN = 'sl',
  BULGARIAN = 'bg',
  LITHUANIAN = 'lt',
  LATVIAN = 'lv',
  ESTONIAN = 'et',
  ALBANIAN = 'sq',
  MALTESE = 'mt',
  ICELANDIC = 'is',
  SWAHILI = 'sw',
  AFRIKAANS = 'af',
  BASQUE = 'eu',
  CATALAN = 'ca',
  GALICIAN = 'gl',
}

export const AVAILABLE_LANGUAGES_LIST = Object.keys(AVAILABLE_LANGUAGE).map((key) => ({
  name: key,
  value: (AVAILABLE_LANGUAGE as any)[key] as AVAILABLE_LANGUAGE,
}));
