export const INTERESTS_LIST_BY_CATEGORY = {
  // Sports & Fitness
  SPORTS_FITNESS: [
    'RUNNING',
    'TRAINING',
    'VOLLEYBALL',
    'CYCLING',
    'CHESS',
    'MARTIAL_ARTS',
    'BASKETBALL',
    'FOOTBALL',
    'HOCKEY',
    'SWIMMING',
    'DIVING',
    'EXTREME_SPORTS',
    'FORMULA_1',
    'MEDITATION',
    'YOGA',
    'ROCK_CLIMBING',
    'TENNIS',
    'TABLE_TENNIS',
    'DANCE_FITNESS',
    'CROSSFIT',
    'PADDLEBOARDING',
    'SKIING_SNOWBOARDING',
    'PARKOUR',
    'NUTRITION',
  ],

  // Entertainment & Leisure
  ENTERTAINMENT_LEISURE: [
    'MOVIES_TV',
    'THEATER',
    'FOOD',
    'MUSEUMS',
    'CONCERTS',
    'SHOPPING',
    'GAMES',
    'BOARD_GAMES',
    'TRAVEL',
    'HIKING',
    'HUMOR',
    'BUSINESS',
    'FINANCE',
    'MANAGEMENT',
    'MUSIC',
    'ART_GALLERIES',
    'ANIME',
    'QUIZZES_PUZZLES',
  ],

  // Education & Hobbies
  EDUCATION_HOBBIES: [
    'SPACE',
    'HISTORY',
    'PETS',
    'DANCING',
    'PHOTOGRAPHY',
    'SINGING',
    'ART',
    'CARS',
    'MOTORCYCLES',
    'COOKING',
    'ARCHITECTURE',
    'LITERATURE',
    'SCIENCE',
    'PSYCHOLOGY',
    'ECOLOGY',
    'INNOVATION',
    'FASHION',
    'POLITICS',
    'WRITING',
    'DESIGN',
    'RELIGION',
    'PHILOSOPHY',
    'MEDICINE',
    'CELEBRITIES',
    'VOLUNTEERING',
    'NEWS',
    'PERSONAL_GROWTH',
    'GARDENING',
    'DIY_PROJECTS',
    'PODCASTS',
    'ASTRONOMY',
    'POETRY',
    'WORLD_CULTURES',
    'ROBOTICS',
    'AI',
    'IT_PROGRAMMING',
    'FISHING',
  ],
};
