import type { Metadata } from 'next';
import '../../styles/_normalize.scss';
import '../../styles/_variables.scss';
import { RootLayout } from '@/layouts/Root';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default RootLayout;
